config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants  do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: :destroy

  root to: 'restaurants#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :delete_all
  
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord

  RATING = (0..5)

  belongs_to :restaurant

  validates :rating, :content, presence:true
  validates :rating, inclusion: { in: RATING }
  validates :rating, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  def index
    @restaurants = Restaurant.all

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
     if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end


  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to restaurant_path(review.restaurant)
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-warning' %>
  </div>
<% end %>
<br>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant, class: 'btn btn-outline-primary'  %>
<div class="position-relative">
  <%= link_to 'Show', @restaurant, class: 'btn btn-outline-success btn-lateral-2'%>
  <%= link_to 'Go Home!', restaurants_path, class: 'btn btn-outline-primary btn-lateral'  %>
</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Category</th>
      <th>Rating</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.category %></td>

        <%total_rate = 0%>
        <%restaurant.reviews.each do |review|%>
        <%total_rate += review.rating%>
        <%end%>
        <%average_rate = total_rate / restaurant.reviews.count%>

        <td class = "text-center"><strong><%= average_rate %></strong></td>

        <td><%= restaurant.phone_number %></td>
        <td><%= link_to 'Show', restaurant, class: 'btn btn-outline-primary' %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-outline-warning' %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you fucking sure?' }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-outline-success' %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant, class: 'btn btn-outline-primary'  %>
<div class="position-relative">
  <%= link_to 'Go Home!', restaurants_path, class: 'btn btn-outline-primary btn-lateral'%>
</div>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone_number %>
</p>

<h4>Reviews:</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <span><em>Rating: </em><strong><%= review.rating %></strong></span><br>
      <span><em>Review: </em><%= review.content %> </span>
      <%= link_to "Remove", review_path(review), method: 'DELETE', data: { confirm: 'Are you fucking sure?' }, class: "tiny-text"%>
    </li>
  <% end %>
</ul>


<%= link_to 'Add A New Review!', new_restaurant_review_path(@restaurant), class: 'btn btn-outline-success'  %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-outline-warning'  %>
<%= link_to 'Go Home!', restaurants_path, class: 'btn btn-outline-primary'  %>

app/views/reviews/new.html.erb
<h1>Add Review to restaurant <%= @restaurant.name %></h1>

<div class="position-relative">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATING %>
    <%= f.button :submit, 'Add This Review!', class: 'btn btn-outline-success' %>
  <% end %>
  <%= link_to 'Go Home!', restaurants_path, class: 'btn btn-outline-primary btn-lateral-3'  %>
</div>